<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Telephonic | About </title>
		<meta name="author" content="Pooja" />
		<meta name="description" content="Telephone promoting website" />
		<link rel="stylesheet" href="../css/style.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
	</head>
    <body id="aboutBody">
         <header>
            <?php 
                include("../attach/nav.php"); 
            ?>
        </header>
        <div class="news">
            <div>
    <h2>SPEECH AND MUSIC BY TELEGRAPH.</h2>
MEN OF SCIENCE TALKING BY WIRE - WHY AND HOW
MUSIC THROUGH HUMAN FLESH – THE TWO TELEPHONES, AND THE DISTINCTION BETWEEN THEM<br />
 On one of the hottest days of last July the telephone made its entry into goods society. Sweltering crowds had for a month been elbowing each other beneath the glass roofs of the Centennial buildings and making the daily discovery that Philadelphia was a hot city. The finest opportunity the world can ever offer to test the virtues of the blue glass was then allowed to pass by without passing experiment. Anything that could have modified Fairmount sunshine would at that time have been heartily welcomed. A goodly number of scientific gentlemen added their perspiring efforts to those pf the crowd, and attempted more minute studies than the ordinary sightseers. There was an immense amount of hard and thorough scientific work done at Philadelphia last year, of which the story has never yet been told. Among the various forms of labor laid out for the Judges of Awards there was one which in its very nature required knowledge, training, patience, care-that of determining the merits of the instruments of precision and research which were exhibited. It is not at all surprising that the gentlemen who had this to do found it no light undertaking in the heat and hurry of those midsummer days. Certainly it was not easy matter to form a correct judgement about a delicate scientific contrivance while thirty thousand American Citizens were prying about the place, staring, pushing, or worse still, asking questions. The men of science wanted a quiet hour for their investigation and they took it, on the day of rest.

<img src="../Images/funnel.jpg" alt="telephone funnel ">
<br />

So, on a sultry Sunday morning hotter according to the thermometer than any day before it last year, a small group of gentlemen entered the Main Building and stationed themselves in the gallery at the east end. The party divided, and half went to each end of the gallery. The great organ was between, and neither half of the party could hear or see the other. Then Prof. A. Graham Bell brought out his telephone. Wires for telegraphing were laid along the gallery; a battery was set at work, and a continuous current was sent along the line. The stations on this line were only two; one at each end of the gallery. At each station there was a little, ordinary electro-magnet, such as people see usually on the table in a small telegraph office, and are in general familiar with. Beside the magnet there was nothing except a few funnels. There were of different shapes, but they agreed in each having one end covered with stretched parchment, like a drum-head. On the centre of each of these drum-heads, outside, a small plate of metal, G. was cemented fast. The diagram shows a more elaborate form of the funnel, one that is provided with a movable ring or hoop (below the letter A) which can be adjusted by set-screws, H, H, By these means parchment, F, F, F, over the end of the funnel, can be made tighter or looser. In the earlier stages of the invention the parchment would be opposite the poles of the electro-magnet, and very close to them; just so that the little piece of metal G, mounted on the parchment, should not quite touch the poles.
<hr />
<h2>THE WIRE SPEAKS WITH HUMAN VOICE</h2>
The Emperor of Brazil, who had joined the party by special invitation, was offered the opportunity of leading off in the experiments, but he courteously valved the precedence. Among the first to make himself heard and recognised through the wire was Prof. J. E. Hilgard. The friends of that genial professor will readily imagine how his eyes twinkled as he put the funnel to his lips and uttered in it the words-
“Dr.Draper! Dr.Draper! Do you hear me?”
Dr.Draper was standing at the other end of the gallery, holding a funnel to his car.
“Why!” he exclaimed, “Tint’s Hilgard’s voice know it by the accent.”
A fact, peculiarities of accent and inflectious of piece were given at least quite as plainly as syllables. The Scotch pronunciation of Sir William Thomsom was recognised at once; Prof. Watson, the able-bodied astronomer of Aun Arbor, Carried on a vigorous conversation with him. Prof. Morton of Hoboken obtained a hearing without difficulty; whether Prof. F. A. P. Barnard did, is more than doubtful.
                There had been many different opinions among these experts as to the possibilities of the instrument. Some of the professors thought it would only give tones and intervals of speech; one was quite sure that it would fail with certain vowels; another was equally certain tha it would be tripped up by consonants. Nobody expected it to do what it actually did to give the whole sound of voice and words naturally. 
           
            Sir William Thomson tested it carefully on these points. One if the party took from his pocket a TRIBUNE and read from it, into the funnel, various paragraphs. It was the paper of the previous Monday, June 26, The Democratic Convention was then in session at St. Louis. One of the paragraphs was from the St. Louis dispatches of THE TRIBUNE, and began, “S. S. Cox has arrived.” The sole adverse criticism of Sir William Thomson on this reading was that he did not hear the “S. S.” distinctly. Another paragraph which was plainly heard throughout, was from the Foreign Summary in the same paper, containing the words ”The Americans in London are preparing to celebrate the Fourth of July”. It is not necessary to repeat here the compliments to Dom Pedro that were wafted on the wire, nor his amiable replies. Neither would it be profitable to report the chaff which passed between the professors such as:
“When you go home you can tell o’ fun on the telephone.”
“No more o’ that, Hal! Already this thing takes my breath away”
It may be hoped that the whole party, after this dip into the mysteries of nature, turned more heartily to those of religion and spent the afternoon in church.
    <img src="../Images/circuit.jpg" alt="circuit">

    
How and why does the telephone transmit the voice! This question could be answered at almost any length. If the reader should wade into the literature of acoustic and electric discovery, taking such excellent guides as Helmholtz and Faraday, he would probably be surprised at its amount and extent. He would be likely also to find the waters very deep and the bottom somewhat uncertain, before he reached dry land and a clear theory of the telephone. As to construction, Prof. Bell’s instrument is simple enough. In the diagram, a continuous flow of electricity is supposed to be proceeding along the wire, from one of the poles of the battery C, through the electromagnet BB, and the cup-like receiver D (having a vibrating lid), and finally back again to the other pole of the battery. The metallic receiver D is said to be more effective than the stretched membrane; practically it combines the funnel, the membrane, and the electro-magnet in a single contrivance. </div>
            <div>It is described as being itself a tubular electro-magnet formed of a single helix eased in soft iron. The lid is represented as only in part secured at the edge, and it is capable of vibration,being attracted or repelled when a current is passing through the helix. The thickness of the lid is about that of cartridge paper. In vibrating it gives out sound. This part of the invention is attributed to M. Nicles, and is 25 years old. In some recent descriptions of Prof. Bell’s apparatus a thin metallic disk is also referred to as having been used for receiving the sounds instead of a stretched membrane. The upper wire E, as shown in the diagram, is a return wire to compare the circuit. The return wire is not needed where connection with the earth can be made at the ends of the line, as it is the ordinary practice of telegraphy.
    <hr />
<h2>WHAT HAPPENS IN THE WIRE</h2>
When the small piece of metal, G, fig. 1, that is mounted on the membrane A, is brought near to the poles of the electro-magnet BB there is a change produced in the strength of the current which is all the time passing along the line. This can be very easily proved. Suppose that at the point X a galvanometer is introduced into the circuit. The galvanometer is an instrument in shape like a compass. The needle which it carries turns from zero point a certain number of degrees, according to the strength of any electric current passing through the instrument. Hence the motion of the needle from the zero point measures the strength of the current. Let us suppose that the current, passing through the wire E, is sufficient to turn the needle from 0° to 50°. Then when a piece of metal, such as the one mounted on the membrane, or indeed any bar of soft iron, is brought close to the poles od the electro-magnet, or laid upon them, the needle of the galvanometer moves at once, and indicates a disturbance of the strength of the current. When the piece of metal is taken away from the electro-magnet, the galvanometer again shows a change in the strength of the current, but its recording needle then moves in an opposite direction. How is this explained? Well, there are several theories which, strange to say, are not particularly in consistent with each other. The current may be conceived of as doing work, and hence losing strength, when it has to pull at the piece of metal presented to the poles; it then has less strength left to show on the galvanometer. Of course the pull is harder and the expenditure of the strength in doing work is greater than the nearer the iron approaches the poles. The other half of this explanation is not so simple. Electricians would say that when the iron is lifted from the poles a reverse current is caused by “induction”. To explain all about “induction” would require too much of space and of patience. If the reader takes kindly to the notion that the strength of the current may be decreased by the work that it does when it attracts the metallic piece G, he can perhaps also conceive that when that piece of metal is removed from poles a certain portion of the work done by the experimenter’s arm in removing the metal may be transmuted into an addition to the electric current in the wire.
    <img src="../Images/wave.jpg" alt="waves from telephone">
					
            
        <hr />
		<h2>		WAVE IN A CURRENT </h2>
A very convenient phrase, indeed, is that which calls the passage of electricity a ”current”. Bearing in mind that it is rather a simple than a fact, it will serve to picture to the mind what happens when the telephone is in operation. Suppose that the current of electricity is represented by a steady stream issuing from a pipe, and running along smoothly. At that point S the current strikes a stone, and is henceforth thrown into waves. After this, the current flows over a dam, T. If the dam is easily shaken, the waves will communicate to it vibrations, and those vibrations will exactly correspond to the waves. Applying this conception to the telephone, the approach of the metal G occasions waves in the electric current, and these are communicated by current to the vibrating lid D. In an exceedingly interactive lecture a few nights ago on the Graham electric light, at Cooper Institute, Dr. G. F. Barker made clear Faraday’s view of this subject. There are rays of force extending in certain well ascertained curves around and to some distance from the poles of a magnet. Whatever contracts or expands that field of force, creates a current of electricity, or where a current already exists, strengthens or weakens it. And this, again, is the effect of the approach of iron to the poles, or its removal from them, as Dr. Barker proved to his audience by the oscillation of a galvanometer, the image of which was magnified and thrown on a screen by electric light. But what actually takes place in the iron of the magnet around which the current flows, is a rearrangement of its molecules, Mr. Joule of England has the credit of discovering, many years ago, that the iron through which an electric current flows is elongated during the passage of the current. A series of exact experiments by Prof. A. M. Mayer, about five years ago, developed a large amount of curious data on this subject. Among other things proved was the fact that a lengthening occurs in an iron rod around which a current is passing; and that the increase in the volume of the rod thus caused, is exactly equaled by a reduction in volume- a shrinkage in the diameter of the rod. Another point ascertained was that the change in dimensions of metal is practically instantaneous; the whole change of length produced by a given strength of electricity is equally great whether the current is turned on very slowly or all at once. Just so in the operation of the telephone, changes in the strength of the current must be wholly and instantly transmitted, not matter what may be their number and variety. Furthermore and this is a very suggestive experiment- if the metal G on the membrane is suffered to rest against the magnitude poles, any sounds sent will still be heard, through faintly. They are reproduced by the molecular movements of the iron itself.
<hr />
                <h2>WHAT THE SPIRITUALIST MEDIUM MISSED</h2>
In point of fact the last-mentioned contrivance is to some extent a reproduction of the earliest telephone, invented by a German-Philip Reiss-about stretched membrane in the sending instrument were caused to make and break an electric current. The received instrument was a single-coil magnet in-closing an iron bar, and was mounted on sounding box. Music could be transmitted by this telephone, and further contrivances developed the sounds received so that they could be heard in a large-hall. But only the sound of the notes- i.e., the pitch of the music-was transmitted. The notes were all equal in strength and quality. A much greater success in sending music by electricity has been latterly achieved by the telephone of Mr. Elisha Gray of Chicago. The public has more or less confounded the performances of this instrument with those of one invented by Prof. Bell. Mr. Gray’s telephone was shown at the Centennial Exhibition, and called forth much interest among the men of science who examined it. Its leading feature is the use of tuning-forks. A tuning-fork may be so introduced into a telegraphic circuit as to make and break the circuit. </div>
                <div>Such a fork, vibrating a certain fixed number of times per second. Four years ago Mr. Gray made a curious discovery as to some means by which this intermittent current can be made audible. If the believers in mesmerism and psychic force had known of it in time, they might have made much capital for their theories out of that discovery and the mystery that enshrouded the performance. Mr. Gray had a violin with a silver plate set in front of it. If the end of wire over which was sent an intermittent current such as has been described was held in the hand, and the fingers of the same hand were lightly rubbed over the silver plate, the note of the tuning-fork at the other end of the line was reproduced, and could be distinctly heard from the violin. A yet more curious result is attained if the violin is made to rotate horizontally, or if there is substituted for it a revolving sounding box the front of which is covered with a sheet od metal. The fingers of the hand holding the telegraph wire are to be pressed against the rotating metallic plate; then the faster the plate revolves, the louder is the reproduced sound. It can be easily heard throughout a large hall. There is evidently a limit to the loudness of the sound, as with high speed operator’s fingers will be too hard rubbed. Why must the human hand intervene? If an exhibitor at a spiritual séance had shown that apparatus in 1873 and asked that question, the men of science could not have answered him. He could have triumphantly turned his revolving fiddle and said with Hamlet- “Ay! There’s the rub!” But when Mr. Gray took this contrivance with him to England and got Prof. Tyndall’s aid in experimenting upon it, another discovery was made which wholly changed the aspect. It was shown that neither the human hand, nor living nerve, nor vitality itself was needful as a medium of communication. Prof. Tyndall reproduced the musical sound when he substituted a piece of salt pork for the human hand!
    <img src="../Images/sound-box.jpg" alt="sounding-box">
    
    <hr />
			<h2>THE SOUNDING BOX RECEIVER</h2>
In Gray’s, as in Bell’s telephone, a continuous current from a main battery is required. The Gray sending instrument is in outward shape a piano of two octaves. The tune to be transmitted must be played on the keys of this piano. Each key has its own tuning-fork, and when a key is depressed a part of the electric current that travels through that particular tuning fork. The mechanism by which the electric current is thus switched on and off the line by a touch to a piano key is somewhat complex, and its detail would not be of interest to the general reader. The receiving instrument is an electro-magnet, K K, mounted by one of its coils and a support, J, upon a sounding box, L. The prong of a tuning fork, M, approaches very nearly but does not quite touch one pole of the magnet; the handle of the fork is connected with the other pole through the support, J. When the apparatus is thus arranged, there must of course be a separate sounding box for every note that the telephone transmits.
        
           <hr />
            <h2>CAPABILITY OF THE MUSICAL TELEGRAPH</h2>
By using in the sending apparatus, in addition to the main current, a current from smaller, special batteries, one for each note, Mr. Gray has achieved a further improvement. By this the intensity of a musical note is given, as well as the note itself. Chords of two or three notes can also be transmitted. It will be seen that the receiving tuning fork selects out from the main current the electric impulses or the making and breaking of the current, which correspond to its own vibration. Hence a receiving tuning fork will only sound when a sending tuning fork of the same note or pitch is transmitting. The practical use which is claimed for this is that by it several message of the ordinary Morse signals may be sent from a central office over a single line, and no one of them will be repeated at any situation except the one for which each message is designed, as every station will have a receiving instrument that sounds to a different note from the others, and the operator at the central office taps for each on a different key. Although the current for the note or pitch is intermittent, its pulsations are so rapid (several hundred in a second) that for telegraphing purposes it may be regarded as a continuous current. The Morse signals make and break this intermittent current just as they would an ordinary one. The receiving operator hears the message in the make and break of Morse signals from his sounding box. In one of the more recent designs for hid telephone, Mr. Gray proposes to put a diaphragm or membrane in front of the opening of the sounding box to catch the vibrations and communicate them to a printing machine, which in turn will print the message in Morse signals or telegraphic tape.
        <hr />
                <h2>A COMPARISON OF TELEPHONES</h2>
It will be seen that the difference between these telephones is very great. The Gray telephone operates by means of tuning forks, and the signals operates by means of tuning forks, and the signals are sent by a make-and-break system, as telegraphic signals usually are. In the Bell telephone the current is not “shunted” or switched; there is nothing done on the make-and-break system either as to vibrations or signals; and finally, the vibrations are the signals. From these radical differences it results also that the Gray telephone can only transmit two of the three characteristics of musical sound; i.e., pitch and intensity, but not quality. So longas the vibration must be transmitted through tuning forks, the Gray telephone can never transmit what Helmholtz has called the “overtones”. These are weaker harmonic notes which accompany the primary tone and offer for each musical instrument; they make the variety to our ears of quality of sound by which we distinguish, for instance, between the notes of a flute and of a violin. These overtones are not given by tuning forks, and cannot be. On the other hand, no matter what may be the height, length, or frequency of the sound waves that strike the stretched membrane in the Bell telephone, their exact counterpart in vibration can be reproduced at the other end of the line. But at best the vibrations in Prof. Bell’s device can only affect a part of the current; they may be essentially feeble, compared with signals on a make-and-break system. If recent accounts are to be trusted, this defect has been measurably overcome by the use of a stronger electro-magnet. Perhaps the harmony which both inventors are desirous of mastering may extend from sound to sense, and the two telephones may some day work literally in concert. When that is done it may be practicable to set up a sound-board behind an orchestra and telegraph its whole performance to a distant city. Meanwhile the public will have plenty of time to form an opinion on the comparative merits of the instruments and to recover from the present confusion of ideas which was so admirably exemplified at Philadelphia by inquiries made in the Main Building for “the talking-machine of Bellham Gray”.
            </div>
        </div>
        <script src="../JS/script.js" defer ></script>
        <?php include("../attach/footer.php")?>
    </body>
</html>